### ISSUE TITLE
Check for non-space whitespace in titles

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/outernet-metadata#7] opened 2015-10-26 16:19 UTC
Titles should not contain any whitespace other than space character (and space equivalents in other langauges). Currently this does not seem to be the case.

**Comment by ben-en** [comment] 2015-10-26 17:55
Where should this be handled? On import?

**Comment by foxbunny** [comment] 2015-10-26 17:58
In the validator.

**Comment by ben-en** [comment] 2015-10-26 18:02
Oh, obviously, as that's where the issue is. Heh.

**Comment by ben-en** [comment] 2015-11-03 16:16
Fixed in 87d4e19b72a2149460d57992a126acf7b0184b31

**Closed as completed by ben-en** 2015-11-03 16:16 UTC
Labels: critical bug
